export const SET_TAB = "SET_TAB"
export const ADD_AET = "ADD_AET"
export const SET_FORM_DATA = "SET_FORM_DATA"
export const ADD_MODALITIES = "ADD_MODALITIES"
export const ADD_QUERY_TO_LIST="ADD_QUERY_TO_LIST"
export const REMOVE_QUERY="REMOVE_QUERY"