// Global actions for apps
export const LOAD_AETS = 'LOAD_AETS'
export const SET_TAB = 'SET_TAB'

// Manual Query Actions
export const SET_RETRIVE_STATUS_STUDY = 'SET_RETRIVE_STATUS_STUDY'
export const SET_RETRIEVE_STATUS_SERIES = 'SET_RETRIEVE_STATUS_SERIES'

// AutoQuery QueryList Actions
export const ADD_QUERY_TO_LIST = 'ADD_QUERY_TO_LIST'
export const ADD_EMPTY_QUERY = 'ADD_EMPTY_QUERY'
export const EDIT_COLUMN_QUERY = 'EDIT_COLUMN_QUERY'
export const REMOVE_QUERY = 'REMOVE_QUERY'
export const EMPTY_QUERY = 'EMPTY_QUERY'

// AutoQuery ResultList Actions
export const ADD_QUERY_RESULT_TO_LIST = 'ADD_QUERY_RESULT_TO_LIST'
export const REMOVE_RESULT = 'REMOVE_RESULT'
export const ADD_RESULT_TO_LIST = 'ADD_RESULT_TO_LIST'
export const EMPTY_RESULTS = 'EMPTY_RESULTS'
export const ADD_SERIES_DETAILS = 'ADD_SERIES_DETAILS'

//ManualQuery Actions
export const SET_MANUAL_QUERY_RETRIEVE_STATUS_SERIES = 'SET_MANUAL_QUERY_RETRIEVE_STATUS_SERIES'
export const ADD_MANUAL_QUERY_RESULT_TO_LIST = 'ADD_MANUAL_QUERY_RESULT_TO_LIST'
export const SET_MANUAL_QUERY_RETRIVE_STATUS_STUDY = 'SET_MANUAL_QUERY_RETRIVE_STATUS_STUDY'
export const ADD_MANUAL_QUERY_SERIES_DETAILS = 'ADD_MANUAL_QUERY_SERIES_DETAILS'

//DeleteTools Actions
export const ADD_STUDY_DELETE_LIST = 'ADD_STUDY_DELETE_LIST'
export const REMOVE_PATIENT_DELETE_LIST = 'REMOVE_PATIENT_DELETE_LIST'
export const REMOVE_STUDY_DELETE_LIST = 'REMOVE_STUDY_DELETE_LIST'
export const DELETE_LIST = 'DELETE_LIST'

//Anon Actions
export const ANONYMIZE_CONTENT = 'ANONYMIZE_CONTENT'

//Export Actions
export const EXPORT_CONTENT = 'EXPORT_CONTENT'
