// Global actions for apps
export const LOAD_AETS = 'LOAD_AETS'
export const SET_TAB = 'SET_TAB'

// AutoQuery QueryList Actions
export const AQ_ADD_QUERY_TO_LIST = 'AQ_ADD_QUERY_TO_LIST'
export const AQ_ADD_EMPTY_QUERY = 'AQ_ADD_EMPTY_QUERY'
export const AQ_EDIT_COLUMN_QUERY = 'AQ_EDIT_COLUMN_QUERY'
export const AQ_REMOVE_QUERY = 'AQ_REMOVE_QUERY'
export const AQ_EMPTY_QUERY = 'AQ_EMPTY_QUERY'

// AutoQuery ResultList Actions
export const AQ_ADD_STUDY_RESULT = 'AQ_ADD_STUDY_RESULT'
export const AQ_ADD_SERIES_DETAILS = 'AQ_ADD_SERIES_DETAILS'
export const AQ_EMPTY_RESULTS = 'AQ_EMPTY_RESULTS'
export const AQ_REMOVE_STUDY_RESULT = 'AQ_REMOVE_STUDY_RESULT'


//ManualQuery Actions
export const SET_MANUAL_QUERY_RETRIEVE_STATUS_SERIES = 'SET_MANUAL_QUERY_RETRIEVE_STATUS_SERIES'
export const ADD_MANUAL_QUERY_RESULT_TO_LIST = 'ADD_MANUAL_QUERY_RESULT_TO_LIST'
export const SET_MANUAL_QUERY_RETRIVE_STATUS_STUDY = 'SET_MANUAL_QUERY_RETRIVE_STATUS_STUDY'
export const ADD_MANUAL_QUERY_SERIES_DETAILS = 'ADD_MANUAL_QUERY_SERIES_DETAILS'

//DeleteTools Actions
export const ADD_DELETE_LIST = 'ADD_DELETE_LIST'
export const REMOVE_PATIENT_DELETE_LIST = 'REMOVE_PATIENT_DELETE_LIST'
export const REMOVE_STUDY_DELETE_LIST = 'REMOVE_STUDY_DELETE_LIST'
export const EMPTY_DELETE_LIST = 'EMPTY_DELETE_LIST'

//Orthanc Content actions
export const ADD_ORTHANC_CONTENT = 'ADD_ORTHANC_CONTENT'
export const REMOVE_ORTHANC_CONTENT_STUDY = 'REMOVE_ORTHANC_CONTENT_STUDY'
export const REMOVE_ORTHANC_CONTENT_PATIENT = 'REMOVE_ORTHANC_CONTENT_PATIENT'

//Anon Actions
export const ADD_ANON_LIST = 'ADD_ANON_LIST'
export const ADD_ANONYMIZED_LIST = 'ADD_ANONYMIZED_LIST'
export const EMPTY_ANON_LIST = 'EMPTY_ANON_LIST'
export const EMPTY_ANONYMIZED_LIST = 'EMPTY_ANONYMIZED_LIST'
export const REMOVE_PATIENT_ANON_LIST = 'REMOVE_PATIENT_ANON_LIST'
export const REMOVE_STUDY_ANON_LIST = 'REMOVE_STUDY_ANON_LIST'
export const REMOVE_STUDY_ANONYMIZED_LIST = 'REMOVE_STUDY_ANONYMIZED_LIST'
export const SAVE_NEW_VALUES = 'SAVE_NEW_VALUES'
export const SAVE_ANON_PROFILE = 'SAVE_ANON_PROFILE'
export const AUTOFILL = 'AUTOFILL'

//Export Actions
export const ADD_EXPORT_CONTENT = 'ADD_EXPORT_CONTENT'
export const REMOVE_STUDY_EXPORT_LIST = 'REMOVE_STUDY_EXPORT_LIST'
export const REMOVE_SERIES_EXPORT_LIST = 'REMOVE_SERIES_EXPORt_LIST'
export const EMPTY_EXPORT_LIST = 'EMPTY_EXPORT_LIST'
